### ISSUE TITLE
unable to save the scale values for the error with the residual_rescale option

### ISSUE THREAD

**Issue by themiyan** [cschreib/slinefit#4]
When running the `save_model ` with the `residual_rescale` option there seems to be a bug in memory assignment with vif? so the scale values are not saved and because of the error none of the other outputs are saved. 

```
/data/themiya/softwares/slinefit/bin/slinefit onedspec_obs100_02076_for_slinefit.fits  z0=3.80 dz=0.1 delta_z=0.0001 num_mc=200 threads=32 width_min=50 width_max=10000 delta_width=1 same_width use_global_chi2 full_range fit_continuum_template verbose lines=[em_halpha,em_n2_6583,em_o3_5007,em_s2_6717,em_hbeta] fit_continuum_template template_dir=/data/themiya/softwares/slinefit/bin/templates/ residual_rescale save_rescaling save_model 


themiya@plexus:/data/themiya/go_2565_slinefit/uds$ ./run_slinefit_uds.sh
note: running slinefit v2.1
note: read input spectrum...
note: reading onedspec_obs100_02076_for_slinefit.fits
note: input spectrum in wavelength unit
note: wavelength coverage: 1.08706 to 4.9536 microns (average cdelt = 0.0116908)
note: fitting 300 spectral elements between 1.08706 and 4.9536 um...
note: ... with 5/5 lines from the database
note: ... and 6 galaxy templates for the continuum
note: best resolution of spectrum: R=286.36
note: linear redshift search
note:  - 57275 redshifts, step = 3.49199e-07
note:  - 10 line widths, step = 1105.56 km/s
[--------------------------------] 57275 100%, 53s elapsed, 0ns left, 53s total


error: /data/themiya/softwares/slinefit/external/include/vif/core/vec.hpp:782: incompatible size in assignment (assigning {0} to {300})


```

**Comment by cschreib** [comment]
Hi Themiya! I see the problem and have pushed a fix for the crash. 

The crash however is a symptom of a real problem; your spectrum has a very coarse resolution, and this doesn't play nice with the `residual_rescale` option as it is currently implemented. Indeed, at the moment `residual_rescale` computes a local rescaling using a small window around each line (8000 km/s by default, but you can change it with `local_continuum_width`). With the spectral resolution you have, this means only 8 spectral elements. This is not very much, and in fact the code discards rescaling values made from less than 10 spectral elements. So you end up with no rescaling at all.

To fix this, you will need to increase the value of `local_continuum_width` to a value > `10*c/R` (`c` speed of light, `R` resolution of your spectrum), so, e.g., `local_continuum_width=11000` should work. But then, you will still only be using ~10 spectral elements to compute the error rescaling, which is the barest minimum. I would recommend using an even larger window, perhaps 50000 km/s. See if that makes any difference.

In case this doesn't work, I've also implemented a fallback method whereby the rescaling is computed globally, rather than locally. You can explicitly request this with the new option `residual_rescale_global`. You can also rely on that if you think the rescaling doesn't need to vary as a function of wavelength.

Please let me know if this does not solve the problem for you, and we can re-open this ;)

**Comment by themiyan** [comment]
This works, thanks very much Corentin. 
I played around a bit, need at least  ~ 15,000km/s+ to be more realistic with PRISM R. However at the end using even a larger vase sometimes leads to sudden variations in the scale value. This happens ~ 2 microns, it maybe a combination of some emission lines and the shape of the LSF (the minimum is ~ this value).  
I think for prism the global value is the best and the reduced chi2 is ~ 1 to 2 in this case;  at least until we fully understand why the NIRSpec pipeline underestimate the errors. I believe this is partly that but also limitation of the SSPs (not so much for the lower R modes though).

**Comment by cschreib** [comment]
Glad that solved it!!
